tests/yaml/S_Bash_Util_0019.yml
tests/yaml/S_Bash_Util_0020.yml
tests/yaml/S_Bash_Util_0021.yml
tests/yaml/S_Bash_Util_0022.yml

PIPE-4961 - New write_output tests.

---

tests/yaml/EXT-S-LX-AU-0001.yml
tests/yaml/EXT-S-LX-AU-0002.yml
tests/yaml/EXT-S-LX-AU-0003.yml
tests/yaml/EXT-S-LX-AU-0004.yml
tests/yaml/EXT-S-LX-AU-0005.yml
tests/yaml/EXT-S-LX-AU-0006.yml
tests/yaml/EXT-S-LX-AU-0007.yml
tests/yaml/EXT-S-LX-AU-0008.yml
tests/yaml/EXT-S-LX-AU-0009.yml
tests/yaml/EXT-S-LX-AU-0010.yml
tests/yaml/EXT-S-LX-AU-0011.yml
tests/yaml/EXT-S-LX-AU-0012.yml
tests/yaml/EXT-S-LX-AU-0013.yml
tests/yaml/EXT-S-LX-AU-0014.yml
tests/yaml/EXT-S-LX-AU-0015.yml
tests/yaml/EXT-S-LX-AU-0016.yml
tests/yaml/EXT-S-LX-AU-0017.yml
tests/yaml/EXT-S-LX-AU-0018.yml

Linux test YMLs for UploadArtifact.

UploadArtifact

---

tests/yaml/S_Matrix_0065.yml
tests/yaml/S_Matrix_MN_010.yml

YMLs to test that step test report are saved.

Adds matrix step test report tests.

---

tests/yaml/S_Bash_0578.yml
tests/yaml/S_Bash_0579.yml
tests/yaml/S_Bash_0580.yml
tests/yaml/S_Bash_0581.yml
tests/yaml/S_Bash_0582.yml
tests/yaml/S_Bash_0583.yml
tests/yaml/S_Bash_0584.yml
tests/yaml/S_Bash_0585.yml

Artifactory Docker registry images in resources and as the build image and that the new variables are set correctly.

Adds tests for projects and build info.

---

tests/yaml/S_Bash_0010.yml
tests/yaml/S_Bash_0032.yml
tests/yaml/S_Bash_0035.yml
tests/yaml/S_Bash_0067.yml
tests/yaml/S_Bash_0068.yml

To accommodate both docker.bintray and releases-docker Docker Images

Updated dockerImages in S_Bash_0010,032,035,067,068 

---

tests/yaml/S_Bash_0589.yml

Checks that the clone is on the right branch and the right depth.

GitRepo shallow clone test.

---

tests/yaml/S_Bash_Util_0023.yml
tests/yaml/S_Bash_Util_0024.yml
tests/yaml/S_Bash_Util_0025.yml
tests/yaml/S_Bash_Util_0026.yml
tests/yaml/S_Bash_Util_Notification.yml

`send_notification` tests with SMTP and updates to the Slack test file (otherwise unused) to send Slack notifications.

SMTP send_notification test.

---

tests/yaml/S_Bash_ApprovalGates_5692_0001.yml
tests/yaml/S_Bash_ApprovalGates_5692_0005.yml
tests/yaml/S_Bash_ApprovalGates_5692_0006.yml
tests/yaml/S_Bash_ApprovalGates_5692_0010.yml
tests/yaml/S_Bash_ApprovalGates_5692_0011.yml
tests/yaml/S_Bash_ApprovalGates_5692_0012.yml
tests/yaml/S_Bash_ApprovalGates_5692_0013.yml

PIPE-5692 - Approval Gates test YMLs.

---

tests/yaml/S-Bash-ApprovalGates-5690-0002.yml
tests/yaml/S-Bash-ApprovalGates-5690-0005.yml
tests/yaml/S-Bash-ApprovalGates-5690-0011.yml
tests/yaml/S-Bash-ApprovalGates-5690-0018.yml
tests/yaml/S-Bash-ApprovalGates-5690-0019.yml
tests/yaml/S-Bash-ApprovalGates-5690-0020.yml
tests/yaml/S-Bash-ApprovalGates-5691-0001.yml
tests/yaml/S-Bash-ApprovalGates-5691-0004.yml
tests/yaml/S-Bash-ApprovalGates-5691-0005.yml
tests/yaml/S-Bash-ApprovalGates-5691-0006.yml
tests/yaml/S-Bash-ApprovalGates-5693-0001.yml
tests/yaml/S-Bash-ApprovalGates-5693-0002.yml
tests/yaml/S-Bash-ApprovalGates-5693-0003.yml
tests/yaml/S-Bash-ApprovalGates-5693-0004.yml
tests/yaml/S-Bash-ApprovalGates-5693-0005.yml
tests/yaml/S-Bash-ApprovalGates-5693-0006.yml
tests/yaml/S-Bash-ApprovalGates-5693-0007.yml

add yamls for PIPE-5693 automation

Feature pipe 5693

---

tests/yaml/S_GoPublishModule_0041.yml

Fixes the S_GoPublishModule_0041 test case now that there are multiple modules in the info.

Fix S_GoPublishModule_0041.

---

tests/yaml/S_Bash_5816_001.yml

New test case for affinity groups.

New affinity group test.

---

tests/yaml/S_LinuxVMDeploy_0001.yml
tests/yaml/S_LinuxVMDeploy_0002.yml
tests/yaml/S_LinuxVMDeploy_0004.yml
tests/yaml/S_LinuxVMDeploy_0005.yml
tests/yaml/S_LinuxVMDeploy_0006.yml
tests/yaml/S_LinuxVMDeploy_0007.yml
tests/yaml/S_LinuxVMDeploy_5950_0008.yml
tests/yaml/S_LinuxVMDeploy_5950_0009.yml
tests/yaml/S_LinuxVMDeploy_5950_0010.yml
tests/yaml/S_LinuxVMDeploy_5950_0011.yml
tests/yaml/S_LinuxVMDeploy_5950_0012.yml
tests/yaml/S_LinuxVMDeploy_5950_0013.yml
tests/yaml/S_LinuxVMDeploy_5950_0014.yml
tests/yaml/S_LinuxVMDeploy_5950_0015.yml
tests/yaml/S_LinuxVMDeploy_5950_0016.yml
tests/yaml/S_LinuxVMDeploy_5950_0017.yml
tests/yaml/S_LinuxVMDeploy_5950_0018.yml
tests/yaml/S_LinuxVMDeploy_5950_0019.yml
tests/yaml/S_LinuxVMDeploy_BLUEGREEN.yml

Tests for linuxVMDeploy rollingUpdate redesign.

PIPE-5950 Tests for linuxVMdeploy bluegreen strat.

---

tests/yaml/S_Bash_0581.yml
tests/yaml/S_Bash_0584.yml
tests/yaml/S_CreateReleaseBundle_6237_011.yml
tests/yaml/S_DockerPush_5849_012.yml
tests/yaml/S_DockerPush_5946_001.yml
tests/yaml/S_GradleBuild_5849_001.yml
tests/yaml/S_HelmPublish_5849_001.yml
tests/yaml/S_HelmPublish_5849_002.yml
tests/yaml/S_MvnBuild_5849_001.yml
tests/yaml/S_NpmPublish_5849_017.yml
tests/yaml/S_NpmPublish_5849_018.yml
tests/yaml/S_PublishBuildInfo_5849_001.yml

Fix builder token headers.

---

tests/yaml/S_Bash_Util_6379_001.yml

Checks that the variables are saved.

PIPE-6379 - Adds utility function case.

---

tests/yaml/S_Bash_Util_6380_001.yml
tests/yaml/S_Bash_Util_6380_002.yml
tests/yaml/S_Bash_Util_6380_003.yml
tests/yaml/S_Bash_Util_6380_004.yml
tests/yaml/S_Bash_Util_6380_005.yml
tests/yaml/S_Bash_Util_6380_006.yml
tests/yaml/S_Bash_Util_6380_007.yml
tests/yaml/S_Bash_Util_6380_008.yml
tests/yaml/S_Bash_Util_6380_009.yml
tests/yaml/S_Bash_Util_6380_010.yml
tests/yaml/S_Bash_Util_6380_011.yml
tests/yaml/S_Bash_Util_6380_012.yml
tests/yaml/S_Bash_Util_6380_013.yml

Test cases for 6380 Bash utility functions.

Feature pipe 6380

---

tests/yaml/S_Bash_Util_5961_001.yml

Multiple test cases in one YML file because of the setup required to run these, which they can all share.

PIPE-5961 - Pull request branch filters.

---

tests/yaml/S_Bash_7229_0001.yml

run variables bug. Now we use approval gates to avoid timing
issues.

PIPE-7229 Change automation strategy for

---

tests/yaml/S_Bash_0053.yml

PIPE-6937 - Fix indentation.

---

tests/npm/package.json
tests/yaml/S_DockerPush_6679_001.yml
tests/yaml/S_GoPublishBinary_6679_001.yml
tests/yaml/S_GoPublishModule_6679_001.yml
tests/yaml/S_GradleBuild_6679_001.yml
tests/yaml/S_MvnBuild_6679_001.yml
tests/yaml/S_NpmPublish_6679_001.yml
tests/yaml/S_PublishBuildInfo_6679_001.yml
tests/yaml/S_XrayScan_6679_001.yml

tests can pass multiple times in a row.

PIPE-7154 make build ids unique so build-scan

---

tests/yaml/S_Bash_Util_6380_013.yml

PIPE-7009 - Increases run variables limit.

---

tests/yaml/S_LinuxVMDeploy_0001.yml
tests/yaml/S_LinuxVMDeploy_0002.yml
tests/yaml/S_LinuxVMDeploy_0003.yml
tests/yaml/S_LinuxVMDeploy_0004.yml
tests/yaml/S_LinuxVMDeploy_0005.yml
tests/yaml/S_LinuxVMDeploy_0006.yml
tests/yaml/S_LinuxVMDeploy_0007.yml
tests/yaml/S_LinuxVMDeploy_5950_0008.yml
tests/yaml/S_LinuxVMDeploy_5950_0009.yml
tests/yaml/S_LinuxVMDeploy_5950_0010.yml
tests/yaml/S_LinuxVMDeploy_5950_0011.yml
tests/yaml/S_LinuxVMDeploy_5950_0012.yml
tests/yaml/S_LinuxVMDeploy_5950_0013.yml
tests/yaml/S_LinuxVMDeploy_5950_0014.yml
tests/yaml/S_LinuxVMDeploy_5950_0015.yml
tests/yaml/S_LinuxVMDeploy_5950_0016.yml
tests/yaml/S_LinuxVMDeploy_5950_0017.yml
tests/yaml/S_LinuxVMDeploy_5950_0018.yml
tests/yaml/S_LinuxVMDeploy_5950_0019.yml
tests/yaml/S_LinuxVMDeploy_BLUEGREEN.yml

steps to fail on reports parsing when there were no testreports.

PIPE-2647 Fix bug where ps1 save_tests caused

---

tests/yaml/S_B_Jen_0017.yml
tests/yaml/S_B_Jen_0018.yml
tests/yaml/S_B_Jen_6485_001.yml
tests/yaml/S_B_Jen_6485_002.yml
tests/yaml/S_B_Jen_6485_003.yml

Three more Jenkins test cases, using an existing Jenkins job.

PIPE-6485 - More Jenkins step tests.

---

tests/yaml/S_Bash_util_4075_001.yml

Just saves a test named total.xml.

PIPE-4075 - New save_tests test.

---

tests/yaml/S_CreateReleaseBundle_7932_001.yml

New test case.  Just a CreateReleaseBundle with `sign:true`.

PIPE-7932 - New CreateReleaseBundle test case.

---

tests/npm/package.json
tests/yaml/S_NpmBuild_5933_007.yml
tests/yaml/S_NpmPublish_5849_017.yml
tests/yaml/S_NpmPublish_5849_018.yml
tests/yaml/S_NpmPublish_5933_004.yml
tests/yaml/S_NpmPublish_5933_005.yml
tests/yaml/S_NpmPublish_5933_006.yml
tests/yaml/S_NpmPublish_5933_007.yml
tests/yaml/S_NpmPublish_5933_008.yml
tests/yaml/S_NpmPublish_5933_009.yml
tests/yaml/S_NpmPublish_5933_010.yml
tests/yaml/S_NpmPublish_6679_001.yml
tests/yaml/S_NpmPublish_8118_001.yml

Updates the package.json used in NpmBuild and NpmPublish tests to use unique versions to avoid conflicts.

PIPE-8118 - Update versions in NpmPublish to be unique.

---

tests/yaml/S_Bash_CancelRun_6110_0001.yml

PIPE-6110 Tests for Cancel Run feature.

---

tests/yaml/S_Bash_8304_001.yml
tests/yaml/S_Bash_8304_002.yml
tests/yaml/S_Bash_8304_003.yml
tests/yaml/S_Bash_8304_004.yml
tests/yaml/S_Bash_8304_005.yml
tests/yaml/S_Bash_8304_006.yml
tests/yaml/S_Bash_8304_007.yml
tests/yaml/S_Bash_8304_008.yml
tests/yaml/S_Bash_8304_009.yml
tests/yaml/S_Bash_8304_010.yml
tests/yaml/S_Bash_8304_011.yml
tests/yaml/S_Bash_8304_012.yml
tests/yaml/S_Bash_8304_013.yml
tests/yaml/S_Bash_Util_8304_001.yml
tests/yaml/S_Bash_Util_8304_002.yml
tests/yaml/S_Bash_Util_8304_003.yml
tests/yaml/S_Bash_Util_8304_004.yml
tests/yaml/S_NpmBuild_8304_001.yml
tests/yaml/S_NpmPublish_8304_001.yml
tests/yaml/S_NpmPublish_8304_002.yml
tests/yaml/S_NpmPublish_8304_003.yml
tests/yaml/S_NpmPublish_8304_004.yml
tests/yaml/S_NpmPublish_8304_005.yml
tests/yaml/S_NpmPublish_8304_006.yml

NpmBuild, NpmPublish, FileSpec, and utility function tests.

PIPE-8304 - NpmBuild and NpmPublish.

---

tests/yaml/S_Bash_8312_000.yml
tests/yaml/S_Bash_8312_001.yml
tests/yaml/S_Bash_8312_002.yml
tests/yaml/S_Bash_8312_003.yml
tests/yaml/S_Bash_8312_004.yml
tests/yaml/S_Bash_8312_005.yml
tests/yaml/S_Bash_8312_006.yml
tests/yaml/S_Bash_8312_007.yml
tests/yaml/S_Bash_8312_008.yml

RemoteFile test cases for Bash.

PIPE-8312 - RemoteFile test cases.

---

tests/yaml/S_BASH_6700_0001.yml
tests/yaml/S_BASH_6700_0002.yml
tests/yaml/S_BASH_6700_0003.yml
tests/yaml/S_BASH_6700_0004.yml
tests/yaml/S_BASH_6700_0005.yml

PIPE-6700 - Add tests for allowing single version

---

tests/yaml/S_PromoteBuild_8308_001.yml
tests/yaml/S_PromoteBuild_8308_002.yml
tests/yaml/S_PromoteBuild_8308_003.yml
tests/yaml/S_PromoteBuild_8308_004.yml
tests/yaml/S_PromoteBuild_8308_005.yml
tests/yaml/S_PromoteBuild_8308_006.yml
tests/yaml/S_PromoteBuild_8308_007.yml
tests/yaml/S_PromoteBuild_8308_008.yml
tests/yaml/S_PromoteBuild_8308_009.yml
tests/yaml/S_PromoteBuild_8308_010.yml
tests/yaml/S_PublishBuildInfo_8308_001.yml
tests/yaml/S_PublishBuildInfo_8308_002.yml
tests/yaml/S_PublishBuildInfo_8308_003.yml
tests/yaml/S_PublishBuildInfo_8308_004.yml
tests/yaml/S_PublishBuildInfo_8308_005.yml
tests/yaml/S_PublishBuildInfo_8308_006.yml
tests/yaml/S_PublishBuildInfo_8308_007.yml
tests/yaml/S_PublishBuildInfo_8308_008.yml
tests/yaml/S_PublishBuildInfo_8308_009.yml
tests/yaml/S_PublishBuildInfo_8308_010.yml

PIPE-8308 - PromoteBuild and PublishBuildInfo tests.

---

tests/yaml/S_Bash_8307_001.yml
tests/yaml/S_DockerBuild_8307_001.yml
tests/yaml/S_DockerPush_8307_001.yml
tests/yaml/S_DockerPush_8307_002.yml
tests/yaml/S_DockerPush_8307_003.yml
tests/yaml/S_DockerPush_8307_004.yml
tests/yaml/S_DockerPush_8307_005.yml
tests/yaml/S_DockerPush_8307_006.yml
tests/yaml/S_DockerPush_8307_007.yml
tests/yaml/S_DockerPush_8307_008.yml
tests/yaml/S_DockerPush_8307_009.yml

PIPE-8307 - DockerBuild and DockerPush.

---

tests/yaml/S_Bash_8307_001.yml

PIPE-8307 - Fix S_Bash_8307_001.

---

tests/yaml/S_CreateReleaseBundle_8310_001.yml
tests/yaml/S_CreateReleaseBundle_8310_002.yml
tests/yaml/S_CreateReleaseBundle_8310_003.yml
tests/yaml/S_CreateReleaseBundle_8310_004.yml
tests/yaml/S_CreateReleaseBundle_8310_005.yml
tests/yaml/S_CreateReleaseBundle_8310_006.yml
tests/yaml/S_CreateReleaseBundle_8310_007.yml
tests/yaml/S_CreateReleaseBundle_8310_008.yml
tests/yaml/S_CreateReleaseBundle_8310_009.yml
tests/yaml/S_CreateReleaseBundle_8310_010.yml

CreateReleaseBundle test cases.

PIPE-8310 - CreateReleaseBundle tests.

---

tests/helmCharts/myChart/Chart.yaml
tests/yaml/S_HelmPublish_5933_025.yml
tests/yaml/S_HelmPublish_5933_026.yml
tests/yaml/S_HelmPublish_5933_027.yml
tests/yaml/S_HelmPublish_5933_028.yml
tests/yaml/S_HelmPublish_5933_029.yml
tests/yaml/S_HelmPublish_5933_031.yml
tests/yaml/S_HelmPublish_5933_032.yml
tests/yaml/S_HelmPublish_5933_033.yml
tests/yaml/S_HelmPublish_5933_034.yml
tests/yaml/S_HelmPublish_5933_035.yml
tests/yaml/S_HelmPublish_8138_001.yml
tests/yaml/S_HelmPublish_8309_001.yml
tests/yaml/S_HelmPublish_8309_002.yml
tests/yaml/S_HelmPublish_8309_003.yml
tests/yaml/S_HelmPublish_8309_004.yml

Updates Bash HelmPublish tests to use unique versions.

PIPE-8309 - Update HelmPublish tests to use different version numbers.

---

tests/helmCharts/simplehelmdeploy/.helmignore
tests/helmCharts/simplehelmdeploy/Chart.yaml
tests/helmCharts/simplehelmdeploy/templates/NOTES.txt
tests/helmCharts/simplehelmdeploy/templates/_helpers.tpl
tests/helmCharts/simplehelmdeploy/templates/deployment.yaml
tests/helmCharts/simplehelmdeploy/templates/ingress.yaml
tests/helmCharts/simplehelmdeploy/templates/service.yaml
tests/helmCharts/simplehelmdeploy/templates/tests/test-connection.yaml
tests/helmCharts/simplehelmdeploy/values.yaml
tests/helmCharts/simplehelmdeploy/values2.yaml
tests/yaml/S_HelmDeploy_0024.yml
tests/yaml/S_HelmDeploy_0026.yml
tests/yaml/S_HelmDeploy_0033.yml
tests/yaml/S_HelmDeploy_5933_013.yml
tests/yaml/S_HelmDeploy_7602_0004.yml
tests/yaml/S_HelmDeploy_7602_0005.yml
tests/yaml/S_HelmDeploy_8138_001.yml
tests/yaml/S_HelmDeploy_8309_001.yml
tests/yaml/S_HelmDeploy_8309_002.yml
tests/yaml/S_HelmDeploy_8309_003.yml
tests/yaml/S_HelmDeploy_8309_004.yml
tests/yaml/S_HelmDeploy_8309_005.yml
tests/yaml/S_HelmDeploy_8309_006.yml

Bash HelmDeploy tests, updating existing to upload to unique locations and new.

PIPE-8309 - Helm tests.

---

tests/yaml/S_HelmDeploy_0013.yml
tests/yaml/S_HelmDeploy_0014.yml
tests/yaml/S_HelmDeploy_0015.yml
tests/yaml/S_HelmDeploy_0016.yml
tests/yaml/S_HelmDeploy_0036.yml

These steps don't do anything, but the test cases will need to be updated at the same time.

PIPE-8309 - Remove unneeded steps.

---

tests/yaml/P_WF_10056_0001.yml
tests/yaml/P_WF_10056_0002.yml

PIPE-10056 tests for 500 error on retrigger with

---

tests/yaml/P_WF_10056_0001.yml
tests/yaml/P_WF_10056_0002.yml

Reverts jfbetapipeorg/Org_test_Automation_bash#212
Wrong repository.

Revert "PIPE-10056 tests for 500 error on retrigger with"

---

tests/yaml/S_Bash_Util_0009.yml

Updates to a directory _without_ an XML file.

PIPE-9869 - Update Bash save_tests test.

---

tests/yaml/S_DockerPush_5933_004.yml
tests/yaml/S_DockerPush_5933_005.yml
tests/yaml/S_DockerPush_8307_003.yml
tests/yaml/S_DockerPush_8307_004.yml

PIPE-10333 - Fix DockerPush YMLs.

---

tests/yaml/S_BASH_7261_0001.yml
tests/yaml/S_BASH_7261_0002.yml

Fix S_BASH_7261_SSHKEY name.

---

tests/yaml/S_Bash_0058.yml
tests/yaml/S_Bash_0076.yml
tests/yaml/S_Bash_10983_0001.yml
tests/yaml/S_Bash_10983_0002.yml

Copies of S-BASH-6152-0001 and S-BASH-6152-0002 to set a node pool and removal of an integration requirement from two others.

PIPE-10983 - Update YML files.
